services:
  db-messenger:
    image: postgres:15
    container_name: messenger-db
    environment:
      POSTGRES_USER: messenger
      POSTGRES_PASSWORD: "1910"
      POSTGRES_DB: messenger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app-messenger:
    build: .
    image: jaba-app
    container_name: messenger-app
    ports:
      - "8080:8080"
    depends_on:
      - db-messenger
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://messenger-db:5432/messenger
      - SPRING_DATASOURCE_USERNAME=messenger
      - SPRING_DATASOURCE_PASSWORD=1910
    volumes:
      - ./uploads:/app/uploads # Пробрасываем папку с аватарками наружу

volumes:
  postgres_data: