spring.application.name=messenger

# Настройки подключения к PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/messenger
spring.datasource.username=messenger
spring.datasource.password=1910
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Настройки сервера
server.port=8080
